name: Build Geode Mod

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  build-windows:
    name: Build Windows
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Download PersistenceAPI Source
      uses: actions/checkout@v4
      with:
        repository: '0x5abe/PersistenceAPI'
        path: 'PersistenceAPI'

    - name: Setup Geode CLI
      uses: geode-sdk/build-geode-mod@main
      with:
        bindings: geode-sdk/bindings
        bindings-ref: main
        combine: false
        sdk: v5.4.1

    - name: Force Native Build Command
      shell: bash
      run: |
        geode build -p windows

  build-android32:
    name: Build Android32
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Download PersistenceAPI Source
      uses: actions/checkout@v4
      with:
        repository: '0x5abe/PersistenceAPI'
        path: 'PersistenceAPI'

    - name: Setup Geode CLI
      uses: geode-sdk/build-geode-mod@main
      with:
        bindings: geode-sdk/bindings
        bindings-ref: main
        combine: false
        sdk: v5.4.1

    - name: Force Native Build Command
      shell: bash
      run: |
        geode build -p android32

  build-android64:
    name: Build Android64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Download PersistenceAPI Source
      uses: actions/checkout@v4
      with:
        repository: '0x5abe/PersistenceAPI'
        path: 'PersistenceAPI'

    - name: Setup Geode CLI
      uses: geode-sdk/build-geode-mod@main
      with:
        bindings: geode-sdk/bindings
        bindings-ref: main
        combine: false
        sdk: v5.4.1

    - name: Force Native Build Command
      shell: bash
      run: |
        geode build -p android64
