name: Build Geode Mod

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
        - name: Windows
          os: windows-latest
          target: Win
        - name: Android32
          os: ubuntu-latest
          target: Android32
        - name: Android64
          os: ubuntu-latest
          target: Android64

    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Android NDK
      if: matrix.config.target == 'Android32' || matrix.config.target == 'Android64'
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r26b

    - name: Fetch PersistenceAPI
      shell: bash
      run: |
        mkdir -p build/geode-deps
        curl -L -o build/geode-deps/sabe.persistenceapi.geode https://github.com
      continue-on-error: true

    - name: Build the mod
      uses: geode-sdk/build-geode-mod@main
      with:
        bindings: geode-sdk/bindings
        bindings-ref: main
        combine: true
        target: ${{ matrix.config.target }}
